input.onButtonPressed(Button.A, function () {
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Double))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Double))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Breve))
    basic.pause(delay)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(988, music.beat(BeatFraction.Whole))
    basic.showString(" P R E S S   B   :)")
    basic.showIcon(IconNames.House)
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("C5 F C5 B A C5 G C5 ", 120)
    basic.showIcon(IconNames.Happy)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(988, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(415, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(311, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(131, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(delay2)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(delay)
    music.playMelody("C5 B G E D C D C ", 120)
    basic.pause(100)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(370, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(277, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(247, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(233, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(220, music.beat(BeatFraction.Breve))
    basic.pause(100)
    music.playTone(196, music.beat(BeatFraction.Breve))
    music.playTone(131, music.beat(BeatFraction.Whole))
    music.playTone(247, music.beat(BeatFraction.Whole))
    music.playSoundEffect(music.createSoundEffect(WaveShape.Sawtooth, 4757, 5000, 164, 255, 3000, SoundExpressionEffect.Tremolo, InterpolationCurve.Curve), SoundExpressionPlayMode.UntilDone)
    music.playTone(208, music.beat(BeatFraction.Whole))
    music.playTone(185, music.beat(BeatFraction.Whole))
    music.playTone(349, music.beat(BeatFraction.Whole))
    music.playTone(370, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playMelody("C C5 B A F E C D ", 1111)
    basic.showString("Hello!")
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(131, music.beat(BeatFraction.Quarter))
    basic.clearScreen()
})
let delay = 0
let delay2 = 0
delay2 = 20
delay = 20
